apiVersion: apps/v1
kind: Deployment
metadata:
  name: db01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db01
  template:
    metadata:
      labels:
        app: db01
    spec:
      containers:
        - name: db01
          image: omaribrahim91/db01:mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: db-password
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: db01
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: db01
