apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', "until nc -z db01 3306; do echo waiting for db01; sleep 5; done"]
        - name: wait-for-mc
          image: busybox
          command: ['sh', '-c', "until nc -z mc01 11211; do echo waiting for mc01; sleep 5; done"]
        - name: wait-for-rmq
          image: busybox
          command: ['sh', '-c', "until nc -z rmq01 5672; do echo waiting for rmq01; sleep 5; done"]
      containers:
        - name: app01
          image: omaribrahim91/app01:tomcat
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"    # Request 100 millicores (0.1 CPU)
              memory: "512Mi" # Request 200MB memory
            limits:
              cpu: "500m"    # Limit to 500 millicores (0.5 CPU)
              memory: "1Gi  " # Limit to 512MB memory
---
apiVersion: v1
kind: Service
metadata:
  name: app01
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: app01
