name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust to your default branch name

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build WAR file with Maven (Dockerized)
        run: |
          docker run --rm -v "$PWD":/app -w /app maven:3.8.7-openjdk-11 mvn clean package

      - name: Build Docker image
        run: docker build -t omaribrahim91/app01:latest .

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push omaribrahim91/app01:latest

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
